name: i18n Automation and Preview Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'QA_TRANSLATION_REPORT.md'
      - 'src/locales/**/*.json'
  pull_request:
    branches:
      - main
    paths:
      - 'QA_TRANSLATION_REPORT.md'
      - 'src/locales/**/*.json'

jobs:
  automate-i18n:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Python dependencies
      run: pip install -r requirements.txt
      working-directory: ./landing-page-i18n

    - name: Parse QA Report and Generate Corrections
      id: parse_report
      run: python scripts/parse_qa_report.py > corrections.json
      working-directory: ./landing-page-i18n

    - name: Load Corrections
      id: load_corrections
      run: echo "corrections=$(cat corrections.json)" >> $GITHUB_OUTPUT
      working-directory: ./landing-page-i18n

    - name: Update Translation Files
      run: python scripts/update_translations.py "${{ steps.load_corrections.outputs.corrections }}"
      working-directory: ./landing-page-i18n

    - name: Install project dependencies
      run: pnpm install
      working-directory: ./landing-page-i18n

    - name: Build project
      run: pnpm run build
      working-directory: ./landing-page-i18n

    - name: Deploy to Netlify (Preview)
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './landing-page-i18n/dist'
        production-branch: 'main'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: 'Deploy from GitHub Actions'
        enable-pull-request-comment: true
        enable-commit-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    - name: Get Netlify Deploy URL
      id: netlify_deploy_url
      run: |
        echo 


          echo "NETLIFY_DEPLOY_URL=$(cat .netlify/deploy-url)" >> $GITHUB_OUTPUT
      working-directory: ./landing-page-i18n

    - name: Comment on PR with Preview URL
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const deploymentUrl = process.env.NETLIFY_DEPLOY_URL;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `✨ **Preview da Landing Page com i18n:**\n\nSeu Pull Request foi automaticamente processado e um preview está disponível em: ${deploymentUrl}\n\nPor favor, revise as traduções e o layout. O relatório de QA foi processado e as correções foram aplicadas.`
          });

    - name: Notify on Push with Production URL
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/github-script@v6
      with:
        script: |
          const deploymentUrl = process.env.NETLIFY_DEPLOY_URL;
          console.log(`✨ **Deploy em Produção da Landing Page com i18n:**\n\nA branch principal foi atualizada e um novo deploy está disponível em: ${deploymentUrl}\n\nO relatório de QA foi processado e as correções foram aplicadas.`);


